
SQLALCHEMY_DATABASE_URI: "sqlite:///kills.db"
SQLALCHEMY_TRACK_MODIFICATIONS: True
FREEZER_DESTINATION: "out/build"
FREEZER_RELATIVE_URLS: True

users:
    Polyhedra:
        "Dodeca Hedron": 1494353377
        "Icosa Hedron": 1010398543
        "Myria Hedron": 90554458
        "Hexa Hedron": 90409532
        "Deca Hedron": 92418985
        "Exa Hedron": 92418936
        "Tetra Hedron": 95189586

